// swift-tools-version: 6.0
// Dev-only harness: compiles the Clarity and ClarityWatch app sources as
// macOS libraries so they can be type-checked on machines without Xcode
// (the real app targets are generated by XcodeGen from project.yml).
// The Clarity/ and ClarityWatch/ entries here are symlinks to ../.
import PackageDescription

let package = Package(
    name: "BuildCheck",
    platforms: [.macOS(.v14)],
    dependencies: [
        .package(path: "../ClarityCore"),
        .package(path: "../ClarityKit"),
    ],
    targets: [
        .target(
            name: "AppBuildCheck",
            dependencies: [
                .product(name: "ClarityCore", package: "ClarityCore"),
                .product(name: "ClarityKit", package: "ClarityKit"),
            ],
            path: "Clarity",
            exclude: ["ClarityApp.swift"],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .target(
            name: "WatchBuildCheck",
            dependencies: [
                .product(name: "ClarityCore", package: "ClarityCore"),
                .product(name: "ClarityKit", package: "ClarityKit"),
            ],
            path: "ClarityWatch",
            exclude: ["WatchApp.swift"],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
    ]
)
